---
Resources:
  OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions: 
          - 
            AttributeName: "OrderId"
            AttributeType: "S"
          - 
            AttributeName: "CustomerId"
            AttributeType: "S"
        KeySchema: # Required
          - 
            AttributeName: "OrderId"
            KeyType: "HASH"
          - 
            AttributeName: "CustomerId"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "orders-table"
        Tags: 
          - Key: CreatedBy 
            Value: serverless
