Resources:
  Deployment:
    Type: 'AWS::ApiGatewayV2::Deployment'
    Properties:
      Description: My deployment
      ApiId: !ImportValue  OrdersHttpApiId

  ApiGwLogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 7

  MyStage:
    Type: 'AWS::ApiGatewayV2::Stage'
    Properties:
      StageName: dev
      Description: dev Stage
      DeploymentId: !Ref Deployment
      ApiId: !ImportValue OrdersHttpApiId
      DefaultRouteSettings:
        ThrottlingBurstLimit: 10
        ThrottlingRateLimit: 10
      AccessLogSettings:
        DestinationArn: !GetAtt [ApiGwLogGroup, Arn]
        Format: >-
          {"requestId":"$context.requestId", "ip": "$context.identity.sourceIp",
          "caller":"$context.identity.caller",
          "user":"$context.identity.user","requestTime":"$context.requestTime","routeKey":"$context.routeKey",
          "status":"$context.status"}